### ISSUE TITLE
Ocean for AKS: missing prerequisites 

### ISSUE THREAD

**Issue by kobster2000** [spotinst/help#1523]
Ocean for AKS has two SW prerequisites missing from the documentation:

1. UUIDGEN
2. JQ

Step 5 of the import process will fail unless you have them installed on your terminal

**Comment by netapp-jmontel** [comment]
@giladshahar , What are these and what should we say in the document?

**Comment by giladshahar** [comment]
@romantsukerman please confirm those are needed as per the aks-kubenet-routetable-access.sh code

**Comment by giladshahar** [comment]
@netapp-jmontel @kobster2000 we're working on removing those prerequisites. will update soon again

**Comment by giladshahar** [comment]
@netapp-jmontel @kobster2000 we have updated the script to not need both of those.
@romantsukerman please confirm it is merged, and so we can close this ask.

**Comment by romantsukerman** [comment]
@giladshahar @netapp-jmontel @kobster2000 we have updated the script (going to push it to S3 in the beginning of the week) to show proper messages to the customer in case he is missing one of the packages.
Unfortunately it is not possible to avoid using those packages during script execution.

**Comment by giladshahar** [comment]
thanks @romantsukerman .
@netapp-jmontel let's add a note under step 5 description that these 2 packages are necessary for a successful run of the script. if possible, link to relevant docs for each. https://stedolan.github.io/jq/download/ could be used for JQ, @romantsukerman any suggestion for uuidgen package? maybe https://command-not-found.com/uuidgen?

**Comment by romantsukerman** [comment]
@giladshahar we can suggest it, or straightly suggest https://packages.debian.org/sid/uuid-runtime , which is a package that contains uuidgen.
