### ISSUE TITLE
Dead link for CloudFormation

### ISSUE THREAD

**Issue by gridley-c** [spotinst/help#1943]
**What happened**:

On this page, the CloudFormation link is dead: https://docs.spot.io/ocean/?id=get-started-with-an-ocean-cluster

Dead link: https://aws.amazon.com/quickstart/architecture/spotinst-ocean-eks/

**What you expected to happen**:
A link to a valid QuickStart

**How to reproduce it (as minimally and precisely as possible):**

Go to page, click on link :-)

**Anything else we need to know:**

**Environment:**

- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by netapp-jmontel** [comment]
Resolved. The dead link has been removed.
