### ISSUE TITLE
Documentation for installation of Ocean controller with Helm does not exist.

### ISSUE THREAD

**Issue by Demorealcloud** [spotinst/help#2588]
[https://docs.spot.io/tutorials/spot-kubernetes-controller/install-with-helm](https://docs.spot.io/tutorials/spot-kubernetes-controller/install-with-helm)

![Screenshot from 2022-09-16 14-26-12](https://user-images.githubusercontent.com/109316345/190696838-7aae6fe5-0a4e-40c1-bc3f-7a101ca0a9a1.png)

**Comment by elinornetapp** [comment]
It looks like you have the wrong URL for this page. Could you let us know where you found it? The correct URL is: [….](https://docs.spot.io/ocean/tutorials/spot-kubernetes-controller/install-with-helm).
Can you please let us know how you got to that URL so we can fix the problem that led you to this URL?
Thank you for your comment.

**Comment by PedroAlpis** [comment]
Hi,
There are actually 2 links broken inside the documentation for integrating GKE, inside [this section](https://docs.spot.io/ocean/getting-started/gke?id=step-3-connectivity), you can see in this piece:

-  "2. Install the Ocean Controller. You can do this using [Helm](https://docs.spot.io/tutorials/spot-kubernetes-controller/install-with-helm) or by running [kubectl](https://docs.spot.io/tutorials/spot-kubernetes-controller/install-with-kubectl) commands."

![Screenshot from 2022-09-22 12-55-06](https://user-images.githubusercontent.com/37458346/191795089-dd4a9a83-e27c-46e9-bd25-d3e1ff29ed64.png)
![Screenshot from 2022-09-22 12-55-18](https://user-images.githubusercontent.com/37458346/191795082-647bc8a8-cac3-4f7d-925b-41ed7778c12e.png)

**Comment by elinornetapp** [comment]
Hello, 
I fixed the links. 
Thank you for bringing this to our attention.

**Comment by elinornetapp** [comment]
The links have been fixed.
