### ISSUE TITLE
Help for Shutdown script in Elastigroup doesn't exist

### ISSUE THREAD

**Issue by tobbra** [spotinst/help#2663]
When setting up Elastigroup in Azure, following the link for the documentation about shutdown scripts, it leads to a page that does not exist.

**Comment by netapp-jmontel** [comment]
Hi @tobbra, can you please send the URL you used so we can check the issue? Many thanks for reporting this!

**Comment by tobbra** [comment]
Seems to be fixed already. It was this link https://docs.spot.io/elastigroup/features-azure/shutdown-script-in-elastigroup-for-azure. I'll close the issue. Thanks for reaching out!

**Comment by tobbra** [comment]
Just noticed, it's not fixed; this is the link that leads to a non-existing page: https://docs.spot.io/elastigroup-for-azure/shutdown-script-in-elastigroup/. You'll find the link when you create and Elastigroup and navigate to the Compute page. In the "Shutdown script" section there's a "Learn more" link which points to the non-existing page.

I think the correct link should be the one from my previous post

**Comment by tobbra** [comment]
Here's another one that doesn't work: https://docs.spot.io/elastigroup/azure/getting-started/import-an-existing-azure-resource

**Comment by elinornetapp** [comment]
Hello, we have fixed the two URLs. Thank you for bringing this to our attention.
