### ISSUE TITLE
Spotinst Documentation 

### ISSUE THREAD

**Issue by icxcn** [spotinst/help#394]
Apparently there is a problem while trying to access the documentation.
<img width="1097" alt="Screenshot 2020-10-23 at 11 51 08" src="https://user-images.githubusercontent.com/19519604/96995532-437ae480-1526-11eb-989c-d07e48ff301f.png">

Ex: https://docs.spot.io/container-management/kubernetes/kubernetes-concepts/spotinst-labels/
Should be: https://docs.spot.io/ocean/features/labels-and-taints

Thanks

**Comment by netapp-jmontel** [comment]
From where are you trying to access https://docs.spot.io/container-management/kubernetes/kubernetes-concepts/spotinst-labels/? Please send me a link to the page it's on.
