### ISSUE TITLE
Links to spot documentation from google search are broken

### ISSUE THREAD

**Issue by liortzur-fiverr** [spotinst/help#415]
For example:
https://docs.spot.io/spotinst-api/elastigroup/amazon-web-services/stateful-api/import-stateful-instance/

**Comment by netapp-jmontel** [comment]
@liortzur-fiverr , we have recently completed a major upgrade of the Spot documentation and API Reference sites. Here are the new URLs:
Spot Documentation: https://docs.spot.io/
Spot API Reference: https://docs.spot.io/api/
We recommend going directly to one of these sites. There you can browse the pages or use the built-in search tools.

**Comment by netapp-jmontel** [comment]
This is fixed now. Links to the API reference (e.g., to "spotinst-api/" and like the one in the example above now go to the new API reference site https://docs.spot.io/api/. This issue can be closed.
