### ISSUE TITLE
AWS ASG docs missing

### ISSUE THREAD

**Issue by michaelcretzman** [spotinst/help#423]
My docs link to a lot of your AWS ASG docs but they are all gone from your docs. Here are the links and titles:

- https://api.spotinst.com/getting-started-create-an-elastigroup-cluster-from-an-existing-asg-auto-scaling-group: Create an Elastigroup Cluster from an Existing ASG (Auto-Scaling Group)
- https://api.spotinst.com/getting-started-create-an-elastigroup-cluster-from-an-existing-elb: Create an Elastigroup Cluster from an Existing ELB (Elastic Load Balancer)
- https://api.spotinst.com/elastigroup-for-aws/tutorials/stateful-tutorials/create-a-stateful-elastigroup-from-scratch: Create A Stateful Elastigroup From Scratch

Where can I link to for these topics?

**Comment by netapp-jmontel** [comment]
@michaelcretzman , we recently completed a major upgrade of the documentation site which is now located at:  https://docs.spot.io/. 
Sorry for the inconvenience. Here are the new URLs to the pages you are looking for:
https://docs.spot.io/elastigroup/tutorials/elastigroup-tasks/join-an-existing-asg
https://docs.spot.io/elastigroup/tutorials/elastigroup-tasks/join-an-existing-elb
Please note that the content on the pages above has been updated.
https://docs.spot.io/elastigroup/tutorials/elastigroup-tasks/create-a-stateful-elastigroup-from-scratch

**Comment by michaelcretzman** [comment]
thanks @netapp-jmontel.

I still get 404s from my Link Checker. When I watch your pages load I see a ? after https://docs.spot.io/ for a split second and then disappear. And then the correct page loads.

I wonder if that ? is causing the 404s.

**Comment by liranp** [comment]
@michaelcretzman We've just added aliases to those links (9b90719), so they should work fine for you. We'll map the others as soon as possible. Regarding the question mark, you can read about it [here](https://github.com/rafgraph/spa-github-pages#how-it-works).
