### ISSUE TITLE
Broken article link

### ISSUE THREAD

**Issue by rodrigo-findhotel** [spotinst/help#459]
In this article `https://spot.io/blog/k8-autoscaler-support/` you are referring to three new topics but they don't exist =/

https://docs.spot.io/ocean/tutorials/ocean-for-aws/import-an-eks-based-ocean-cluster/
https://docs.spot.io/ocean/tutorials/ocean-for-gke/create-an-ocean-cloud-cluster/
https://docs.spot.io/container-management/kubernetes-2/kops/1_15/clusters/

**Comment by netapp-jmontel** [comment]
@rodrigo-findhotel,
Thanks for letting us know. We have recently released a major upgrade of our documentation site. The new site is at: docs.spot.io
The pages you were looking for can be found here:
https://docs.spot.io/ocean/getting-started/eks/join-an-existing-cluster
https://docs.spot.io/ocean/getting-started/eks/create-a-new-cluster
https://docs.spot.io/ocean/tools-and-integrations/kops/
Thank you

**Comment by rodrigo-findhotel** [comment]
Thank you!
