### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by stevenfeltner** [spotinst/help#468]
On this page: https://docs.spot.io/elastigroup/tools-integrations/elastic-mapreduce/

On step 4 there is a link to: https://api.spotinst.com/integration-docs/elastigroup/services-integrations/elastic-mapreduce/scaling-policies-for-emr/

Can we correct this link to: https://docs.spot.io/elastigroup/tools-integrations/elastic-mapreduce/scaling-policies-for-emr

**Comment by netapp-jmontel** [comment]
This is fixed. Thanks for reporting.
